---  
title: "SCAPES - Data Management Plan"  
author: "David Simons"  
date: "2024-02-05"  # Replace with the current date  
output:  
  pdf_document:  
    toc: true
    toc_depth: 4
    number_sections: true
    includes:  
      in_header: styles.tex  
---  

# Qualitative data  

## Participatory Rural Assessment  

How will data be collected?    
What form will this data take?  
How/where will it be stored?  
What will the data include?  
What are the variables/parameters of the data?  
How will data be cleaned/processed?  
How will the data be anonymised/participants protected? Will data be shared? If so, how?  

# Quantitative data  

## Community questionnaires  

Questionnaires have been designed as XLSForms and are implemented using the Kobo platform. Data is collected on local devices and sent to the KoboToolbox server (<https://kf.kobotoolbox.org/>) for the SCAPES project. Access can be provided for data entry, modification and download. An unprocessed data set can be downloaded directly from the KoboToolbox server.  

Alternatively, a project has been created to pull the data and format it using R.  

### R Repository for data processing  

The `robotoolbox` R package is used to download the data locally through the Kobo API. This approach uses the `dm` R package to handle the grouped repeats in the questionnaire and the `haven` R package to handle variable structure (e.g., labelled factors).  

Within the `dm` structure repeats within the questionnaire form unique rows in a linked dataframe.  

``` {r dm-description, message = FALSE, warning = FALSE}  

library(here)  
library(dm)  
library(dplyr)  
library(readr)  

dm <- read_rds(here("data", "h_data", "h_data_dm_2024-02-05.rds"))  

knitr::kable(tibble(`Table names` = names(dm),  
                    `Number of records` = sapply(dm, function(x) nrow(x)),  
                    `Links to households` = sapply(dm, function(x)   
                      length(unique(x$`_parent_index`)))))  

dm_draw(dm)  

```  

Within questionnaires these repeats may be conditional and so each main questionnaire may be associated with none or many indexed repeats.  

### Household questionnaire:  

:::: {.householdbox data-latex=""}  

\footnotesize  

**Variable Name:** `start`  

**Description:** Formatted datetime when the questionnaire entry was created.  

**Type of Data:** Datetime  

------------------------------------------------------------------------ 

**Variable Name:** `end`  

**Description:** Formatted datetime when the questionnaire date entry was completed. This may not equate to the length of data collection as data may be added later (e.g., images).  

**Type of Data:** Datetime  

------------------------------------------------------------------------ 

**Variable Name:** `date`  

**Description:** Likely not needed but was used for internal questionnaire logic. Similar to end in that it records the date of the most recent data entry in the form.  

**Type of Data:** Date  

**Format:** %Y\_%m\_%d  

------------------------------------------------------------------------ 

**Variable Name:** `interviewer_id`  

**Description:** Name of the interviewer who conducted the interview.  

**Type of Data:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Diana (Code: 1)  
- Option 2: Helen (Code: 2)  
- Option 3: Nzube (Code: 3)  
- Option 4: Sunday (Code: 4)  
- Option 5: Other (Code: 5)  

**Relationships with other variables:** `interviewer_id_other` contains the free-text entry if other is selected.  

------------------------------------------------------------------------ 

**Variable Name:** `community`  

**Description:** Community questionnaire was conducted in.  

**Type of Data:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Dyegh (Akwa Kwasi) (Code: dyegh)  
- Option 2: Ikyogbakpev (Akwa Kwasi) (Code: ikyogbakpev)  
- Option 3: Zugu (Code: zugu)  
- Option 4: Okimbongha (Code: okimbongha)  
- Option 5: Ogamanna (Code: ogamanna)  
- Option 6: Ofonekom (Code: ofonekom)  
- Option 7: Ezeakataka (Code: ezeakataka)  
- Option 8: Enyandulogu (Code: enyandulogu)  
- Option 9: Offianka (Code: offianka)  

------------------------------------------------------------------------ 

**Variable Name:** `consent_household`  

**Description:** Whether consent for data collection has been provided.  

**Type of Data:** Binary  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `household_number`  

**Description:** Identification number of the household this questionnaire pertains to.  

**Type of Data:** Integer  

**Validation Rules:** Combined with community to produce a unique identifier for a household. Data validation during processing to ensure each household is uniquely identified.  

------------------------------------------------------------------------ 

**Variable Name:** `multiple_family_household`  

**Description:** Are members from this household all from the same family? See protocol for definitions used for household and family.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `n_people`  

**Description:** The number of individuals currently living within the household. Includes those who come and go on a regular basis or are current students away for school.  

**Type of Data:** Integer  

\mydoublerule{}  
\centering
\Large 
\textcolor{blue!80!black}{\textbf{Repeat Section: Household members demographic will be repeated for each member of the household}}
\color{black}
\raggedright
\footnotesize

---

**Variable Name:** `sex_person`  

**Description:** The sex of the individual.  

**Type of Data:** Binary  

**Options for Responses:**  
- Female (Code: 1)  
- Male (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `baby`  

**Description:** Are they less than 1 year old?  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `age`   

**Description:** The age of the individual, in years. Only asked for those \>1 year old.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `age_baby`  

**Description:** The age of the individual in months. Only asked for those \<1 year old.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `permanent_transient`  

**Question:** In the last year, was this individual regularly resident within this household?  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

\centering
\normalsize 
\textcolor{blue!80!black}{\textbf{End of household member repeat}}
\color{black}
\raggedright
\footnotesize

\mydoublerule{}  

**Variable Name:** `compound`  

**Question:** Is this household within a compound?  

**Description:** A compound can be an enclosed area. A compound can also be a clear but defined area.  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `multiple_households`  

**Question:** Do any other households live in the same compound?  

**Description:** Only asked if the answer to the `compound` question is Yes.  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `n_in_other_households`  

**Question:** How many people live in this compound?  

**Description:** Not including those that are in the focal household. Only asked if the answer to the `multiple_households` question is Yes.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `other_household_activities`  

**Question:** Which of the following activities occur regularly with these other households?  

**Description:** Only asked if the answer to the `multiple_households` question is Yes.  

**Type of Data:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Sleeping (Code: sleeping)  
- Option 2: Eating (Code: eating)  
- Option 3: Cooking (Code: cooking)  
- Option 4: Hunting (Code: hunting)  
- Option 5: Farming (Code: farming)  
- Option 6: None (Code: none)  
- Option 7: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `other_household_activities_specify`  

**Description:** Captures other activities which may be conducted with the focal household only if other is selected in `other_household_activities`  

**Type of Data:** Free text  

------------------------------------------------------------------------ 

**Variable Name:** `household_ethnicity_same`  

**Question:** Do all members of this household identify as the same ethnicity?  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `household_ethnicity`  

**Question:** What ethnicity is the household?  

**Description:** Only asked if the answer to the `household_ethnicity_same` question is Yes.  

**Type of Data:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Igbo (Izzi) (Code: igbo_izzi)  
- Option 2: Igbo (Other) (Code: igbo_other)  
- Option 3: Membe (Code: membe)  
- Option 4: Tiv (Code: tiv)  
- Option 5: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `other_ethnicity_household`  

**Description:** Only asked if the answer to `household_ethnicity` is other  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `household_religion_same`  

**Question:** Do all members of this household share the same religion?  

**Type of Data:** Binary (Yes or No)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `household_religion`  

**Question:** What religion is the household?  

**Description:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Christian (Code: christian)  
- Option 2: Muslim (Code: muslim)  
- Option 3: Traditionalist (Code: traditionalist)  
- Option 4: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `household_religion_other`  

**Description:** Only asked if the answer to `household_religion` is other  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `n_compound`  

**Question:** How many buildings or other structures are there in the compound?  

**Description:** This variable represents the count of buildings or other structures within the compound.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `n_individual_buildings`  

**Question:** How many individual buildings does the household use regularly?  

**Description:** This variable represents the count of individual buildings regularly used by the household.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `building_owned`  

**Question:** Are these buildings owned by your household?  

**Description:** This variable indicates whether the buildings are owned by the household.  

**Type of Data:** Factor with labels associated with values.  

**Options for Responses:**  
- Option 1: Own themselves (Code: own_themselves)  
- Option 2: Owned by other members of the family (Code: own_family)  
- Option 3: Rented from a non-family member (Code: rented)  
- Option 4: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `building_owned_other`  

**Description:** This question appears if other is selected in `building_owned`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `n_multi_room`  

**Question:** How many multi-room buildings does this household regularly use?  

**Description:** This variable represents the count of multi-room buildings regularly used by the household.  

**Type of Data:** Integer  

------------------------------------------------------------------------ 

**Variable Name:** `n_single_room`  

**Question:** How many single-room buildings does this household regularly use?  

**Type of Data:** Integer  

\mydoublerule{}  
\centering
\Large 
\textcolor{blue!80!black}{\textbf{Repeat Section: Multi-room buildings will be added, one per repeat}}
\color{black}
\raggedright
\footnotesize  

---

**Variable Name:** `building_purpose`  

**Question:** What does the household use this building for?  

**Description:** For each building used by a household this variable captures information on what purpose it is used for.  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Sleeping (Code: sleeping)  
- Option 2: Food preparation (Code: food_preparation)  
- Option 3: Cooking (Code: cooking)  
- Option 4: Eating (Code: eating)  
- Option 5: Socialising/Parlour (Code: socialising_parlour)  
- Option 6: Cooked food storage (Code: food_storage)  
- Option 7: Packaged food storage (Noodle, Indomie etc.)  
 (Code: packaged_food_storage)  
- Option 8: Crop storage (Garri, Rice, Yam etc.)  
 (Code: crop_storage)  
- Option 9: Seed storage (Code: seed_storage)  
- Option 10: Animal storage (Chicken, Goat etc.)  
 (Code: animal_storage)  
- Option 11: Other storage (Code: other_storage)  
- Option 12: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `specify_building_purpose`  

**Description:** Only asked if other is selected as one of the options in `building_purpose`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `building_location`  

**Question:** Where is the building located?  

**Type of Data:** Factor with labels associated with values  

**Options for Responses:**  
- Option 1: Within the compound (Code: compound)  
- Option 2: No compound, within the village (Code: no_compound)  
- Option 3: Elsewhere in the village, outside of the compound (Code: village)  
- Option 4: In the field, outside of the compound (Code: fields)  
- Option 5: In a different village (Code: other_village)  
- Option 6: In a different town/city (Code: in_town)  
- Option 7: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `specify_building_location`  

**Description:** Only asked if other is selected as the option in `building_location`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `roof_material`  

**Question:** What is the roof made of?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Mat/thatch (Code: mat_thatch)  
- Option 2: Zinc/metal (Code: zinc_metal)  
- Option 3: Deck  (Code: deck)  
- Option 4: None (Code: none)  
- Option 5: Other (Code: other)  

**Definitions:**    

- Roof - refers to external material of the roof  
- Deck - ...  

------------------------------------------------------------------------ 

**Variable Name:** `roof_other`  

**Description:** Only asked if other is selected as the option in `roof_material`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `wall_material`  

**Question:** What are the walls made of?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Mud block (Code: mud_block)  
- Option 2: Brick (Code: brick)  
- Option 3: Cement blocks (Code: cement_block)  
- Option 4: Plaster (Code: plaster)  
- Option 5: Wood (Slats, Lumber etc.) (Code: wood)  
- Option 6: Trees/Sticks (Code: wood_other)  
- Option 7: Other (Code: other)  

**Definitions:**    

- Mud block - an unfired mud block  
- Brick - a fired block  
- Plaster - ...  

------------------------------------------------------------------------ 

**Variable Name:** `walls_other`  

**Description:** Only asked if other is selected as the option in `wall_material`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `door_material`  

**Question:** What is the door of the main entrance made of?  

**Type of Data:** Select one  

**Options for Responses:**  
- Option 1: Wood (Code: wood)  
- Option 2: Metal (Code: metal)  
- Option 3: None (Code: none)  
- Option 4: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `door_other`  

**Description:** Only asked if other is selected as the option in `door_material`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `window_material`  

**Question:** What are the windows made of?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Permanently open (Code: permanently_open)  
- Option 2: Permanently closed (Code: permanently_closed)  
- Option 3: Wooden shutters (Code: wooden_shutters)  
- Option 4: Glass panes (Code: glass)  
- Option 5: Mosquito net (Code: screen)  
- Option 6: Metal grill/sheet (Code: metal)  
- Option 7: No windows (Code: none)  
- Option 8: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `specify_window`  

**Description:** Only asked if other is selected as the option in `window_material`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `ceiling_material`  

**Question:** What material is used for the ceiling?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Mat/thatch (Code: mat_thatch)  
- Option 2: Wood (Code: wood)  
- Option 3: Cement (Code: cement)  
- Option 4: Synthetic (Code: synthetic)  
- Option 5: Sack bag/Carpet/Lino (Code: lining)  
- Option 6: No ceiling (Code: no_ceiling)  
- Option 7: Other (Code: other)  

**Definitions:**    

- Sack bag/Carpet/Lino - ...  

------------------------------------------------------------------------ 

**Variable Name:** `specify_ceiling`  

**Description:** Only asked if other is selected as the option in `ceiling_material`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `ceiling_storage`  

**Question:** Is there anything stored between the ceiling and the roof?  

**Type of Data:** Binary (yes/no)  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

------------------------------------------------------------------------ 

**Variable Name:** `storage_items_ceiling`  

**Question:** What is stored in this space?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Cooked food (Code: cooked_food)  
- Option 2: Uncooked food (Code: uncooked_food)  
- Option 3: Packaged food (Code: packaged_food)  
- Option 4: Crops for sale (Code: crops_for_sale)  
- Option 5: Crops for household use (Code: crops_for_household_use)  
- Option 6: Seeds for sale (Code: seeds_for_sale)  
- Option 7: Seeds for household use (Code: seeds_for_household_use)  
- Option 8: Clothing (Code: clothing)  
- Option 9: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `ceiling_storage_other`  

**Description:** Only asked if other is selected as the option in `storage_items_ceiling`  

**Type of Data:** Free-text  

------------------------------------------------------------------------ 

**Variable Name:** `floor`  

**Question:** What is the floor made of?  

**Type of Data:** Character with each option in a string separated by a space  

**Options for Responses:**  
- Option 1: Mud (Code: mud)  
- Option 2: Cement (Code: cement)  
- Option 3: Tile (Code: tile)  
- Option 4: Other (Code: other)  

------------------------------------------------------------------------ 

**Variable Name:** `internal_door`  

**Question:** Are there doors between the rooms in the building?  

**Description:** This variable indicates whether there are doors between the rooms in the building.  

**Type of Data:** Single-select with binary responses.  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

--- 

**Variable Name:** `internal_door_fit`  

**Question:** Do the doors fit well within the building?  

**Description:** This variable indicates whether the doors fit well within the building. i.e., If your finger can fit through any space in the door, or between the door and the frame, it does not fit well.  

**Type of Data:** Single-select with binary responses.  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

--- 

**Variable Name:** `rooms_in_building`  

**Question:** How many rooms are there in this building?  

**Description:** This variable captures the number of rooms within the same building, including kitchens, bedrooms, storerooms, parlors, etc.  

**Type of Data:** Integer  

--- 

**Variable Name:** `n_household_sleep`  

**Question:** How many people from this household sleep in this building?  

**Description:** This variable indicates the number of people from this household who sleep in this building.  

**Type of Data:** Integer  

--- 

**Variable Name:** `sleep_same_room`  

**Question:** Does everyone from this household that sleeps in this building sleep in the same room?  

**Description:** This variable indicates whether everyone from this household who sleeps in this building sleeps in the same room.  

**Type of Data:** Single-select with binary responses.  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

--- 

**Variable Name:** `n_rooms_household_sleep`  

**Question:** How many different rooms do people from this household sleep in?  

**Description:** This variable captures the number of different rooms in which people from this household sleep.  

**Type of Data:** Integer  

--- 

**Variable Name:** `other_household_sleep`  

**Question:** Do members of a different household sleep in this building?  

**Description:** This variable indicates whether members of a different household sleep in this building.  

**Type of Data:** Single-select with binary responses.  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

--- 

**Variable Name:** `other_household_sleep_shared`  

**Question:** Do members of a different household sleep in the same space/place as members of this household?  

**Description:** This variable indicates whether members of a different household sleep in the same space/place as members of this household.  

**Type of Data:** Single-select with binary responses.  

**Options for Responses:**  
- Yes (Code: 1)  
- No (Code: 0)  

--- 

**Variable Name:** `n_other_household_sleep_multi`  

**Question:** How many members of a different household sleep in this building?  

**Description:** This variable captures the number of members of a different household who sleep in this building.  

**Type of Data:** Integer  

--- 

**Variable Name:** `rodents_enter_building`  

**Question:** Do any rats enter this building?  

**Description:** This variable indicates whether any rats are known to enter this building.  

**Type of Data:** Single-select with three responses  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodents_in_building`  

**Question:** Do any rats live in this building?  

**Description:** This variable indicates whether any rats are known to live in this building.  

**Type of Data:** Single-select with three responses   

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodents_in_building_evidence`  

**Question:** How do you know rats live here?  

**Description:** This variable captures the evidence of rats living in the building.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: See live rats (Code: see_live_rats)  
- Option 2: See dead rats (Code: see_dead_rats)  
- Option 3: See rat urine (Code: see_rat_urine)  
- Option 4: See rat faeces (Code: see_rat_faeces)  
- Option 5: See rat burrows (Code: see_rat_burrows)  
- Option 6: Hear them (Code: hear_them)  
- Option 7: Smell them (Code: smell_them)  
- Option 8: Direct contact with rats (Code: direct_contact)  
- Option 9: Seen the damage they have done to items (Code: item_damage)  
- Option 10: Other (Code: other)  

--- 

**Variable Name:** `rodents_in_building_specify`  

**Question:** Please specify.  

**Description:** This variable allows for specifying other evidence of rats living in the building. Only asked if other is selected in `rodents_in_building_evidence`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `rodent_faeces_multi_sleep`  

**Question:** Do you ever see the excreta/shit of rats in the places where people sleep?  

**Description:** This variable indicates whether rat excreta are observed in sleeping areas.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodent_sleeping_contact_multi`  

**Question:** Has anyone been bitten or scratched by a rat while sleeping in this building?  

**Description:** This variable indicates whether there has been any contact that could potentially result in direct pathogen transmission with rats while sleeping. Sleeping areas may not be the same thing as bedrooms as individuals may sleep in additional rooms of the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `mastomys_multi`  

**Question:** Do you notice a rat called *Mastomys natalensis* (the multimammate rat, or the rat with many offspring) in this building?  

**Description:** This variable captures awareness of the presence of *Mastomys natalensis* in the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `mastomys_timing_multi`  

**Question:** What time of the day do you see this rat?  

**Description:** This variable captures the timing of *Mastomys natalensis* sightings.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Daytime (Code: daytime)  
- Option 2: Nighttime (Code: nighttime)  
- Option 3: Anytime (Code: anytime)  

--- 

**Variable Name:** `mastomys_season_multi`  

**Question:** Which season do you see them in?  

**Description:** This variable captures the seasonality of *Mastomys natalensis* sightings.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Dry (Code: dry)  
- Option 2: Rainy (Code: rainy)  
- Option 3: All seasons (Code: all_seasons)  

--- 

**Variable Name:** `designated_kitchen`  

**Question:** Is there a room that is designated as the kitchen in this building?  

**Description:** This variable indicates whether there is a room designated as the kitchen in the building. Most kitchen activities occur outside but some preparation may occur within buildings or the kitchen may be attached to the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `sleep_in_kitchen`  

**Question:** Do people from this household regularly sleep in the room that is designated as the kitchen?  

**Description:** This variable captures whether individuals from the household regularly sleep in the room designated as the kitchen. Only asked if the answer to `designated_kitchen` is Yes.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `n_sleep_in_kitchen`  

**Question:** How many individuals from this household sleep in the kitchen?  

**Description:** This variable indicates the number of individuals from the household who regularly sleep in the kitchen. Only asked if the answer to `sleep_in_kitchen` is Yes.  

**Type of Data:** Integer  

--- 

**Variable Name:** `rodent_damage_kitchen`  

**Question:** Do rats eat or destroy food or ingredients in the kitchen?  

**Description:** This variable captures whether rats cause damage to food or ingredients in the kitchen. It considers the damage they do to household items stored within kitchens.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  

- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodent_damage_kitchen_items`  

**Question:** What do rats eat or destroy in the kitchen?  

**Description:** This variable captures the items that rats eat or destroy in the kitchen.  

**Type of Data:** Multi-select  

**Options for Responses:**   

- Option 1: Prepared but uncooked food (Garri, Pounded Yam etc.) (Code: uncooked_food)  
- Option 2: Other ingredients for cooking (Spices, Dried Fish etc.) (Code: ingredients)  
- Option 3: Cooked food (Code: cooked_food)  
- Option 4: Rice for cooking (Code: rice)  
- Option 5: Yams for cooking (Code: yam)  
- Option 6: Groundnut for cooking (Code: groundnut)  
- Option 7: Other crops for cooking (Code: other_crops)  

--- 

**Variable Name:** `specify_other_kitchen_items`  

**Question:** Please specify other items that rats eat or destroy in the kitchen.  

**Description:** This variable allows for specifying other items that rats may eat or destroy in the kitchen. This question is only asked if other_crops is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `prepared_food_damage`  

**Question:** How much of the prepared food kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to prepared but uncooked food kept in the kitchen by rats. This question is only asked if uncooked_food is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `cooked_food_damage`  

**Question:** How much of the cooked food kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to  cooked food kept in the kitchen by rats. This question is only asked if cooked_food is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `rice_damage`  

**Question:** How much of the rice kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to rice stored in the kitchen by rats. This question is only asked if rice is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `yam_damage`  

**Question:** How much of the yam kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to yams stored in the kitchen by rats. This question is only asked if yam is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `groundnut_damage`  

**Question:** How much of the groundnut kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to groundnut stored in the kitchen by rats. This question is only asked if groundnut is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `ingredients_damage`  

**Question:** How much of the other ingredients kept in this kitchen is damaged?  

**Description:** This variable attempts to quantify the extent of damage to other crops stored in the kitchen by rats. This question is only asked if other_crops is selected in the `rodent_damage_kitchen_items`.  

**Type of Data:** Single-select with three responses.  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

We do not collect information on the quantity of other ingredients that may be stored being damaged by rodents.  

--- 

**Variable Name:** `designated_store`  

**Question:** Is there a room that is designated to store food, crops, or seed in this building?  

**Description:** This variable indicates whether there is a room designated to store food, crops, or seed in the building.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `cooked_food_in_store`  

**Question:** Do you ever store cooked food in this same store room?  

**Description:** This variable captures whether cooked food is stored in the same store room designated for food, crops, or seeds. Only asked if 'Yes' is selected in `designated_store`.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `sleep_in_store`  

**Question:** Do people sleep in the room that is designated as storage for food, crops, or seeds?  

**Description:** This variable indicates whether people sleep in the room designated as storage for food, crops, or seeds. Only asked if 'Yes' is selected in `designated_store`.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `n_sleep_in_store`  

**Question:** How many individuals from this household sleep in the storeroom(s)?  

**Description:** This variable indicates the number of individuals from this household who sleep in the storeroom(s). Only asked if 'Yes' is selected in `designated_store` and 'Yes' is selected in `sleep_in_store`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `rodent_damage_store`  

**Question:** Do rats eat or destroy food or harvested crops in the storeroom?  

**Description:** This variable captures whether rats eat or destroy food or harvested crops in the storeroom. Harvested crops include everything that you grow yourself.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_damage_store_items`  

**Question:** What do rats eat or destroy in this storeroom?  

**Description:** This variable captures what rats eat or destroy in the storeroom. Only asked if 'Yes' is selected in `rodent_damage_store`.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Cooked food (Code: cooked_food)  
- Option 2: Ingredients for cooking (Code: ingredients)  
- Option 3: Packaged food (Code: packaged_food)  
- Option 4: Harvested crops for household use (Code: harvested_crops_use)  
- Option 5: Harvested crops for sale (Code: harvested_crops_sale)  
- Option 6: Seed stock for household use (Code: seed_use)  
- Option 7: Seed stock for sale (Code: seed_sale)  
- Option 8: Other items (Code: other)  

--- 

**Variable Name:** `specify_other_store`  

**Question:** Specify other items  

**Description:** This variable allows specifying other items that rats eat or destroy in the storeroom. Only asked if 'Other items' is selected in `rodent_damage_store_items`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `cooked_food_damage_store`  

**Question:** How much of the cooked food kept in this storeroom is damaged?  

**Description:** This variable indicates the extent of damage to the cooked food kept in the storeroom. Only asked if 'Cooked food' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `ingredients_damage_store`  

**Question:** How much of the ingredients for cooking are damaged?  

**Description:** This variable indicates the extent of damage to the ingredients for cooking kept in the storeroom. Only asked if 'Ingredients for cooking' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `uncooked_food_damage_store`  

**Question:** How much of the uncooked food kept in this storeroom is damaged?  

**Description:** This variable indicates the extent of damage to the uncooked food kept in the storeroom. Only asked if 'Prepared but uncooked food' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `packaged_food_damage_store`  

**Question:** How much of the packaged food kept in this storeroom is damaged?  

**Description:** This variable indicates the extent of damage to the packaged food kept in the storeroom. Only asked if 'Packaged food' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `crops_use_damage_store`  

**Question:** How much of the crops for household use is damaged?  

**Description:** This variable indicates the extent of damage to the crops for household use kept in the storeroom. Only asked if 'Harvested crops for household use' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `crops_sale_damage_store`  

**Question:** How much of the crops for sale is damaged?  

**Description:** This variable indicates the extent of damage to the crops for sale kept in the storeroom. Only asked if 'Harvested crops for sale' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `seed_use_damage_store`  

**Question:** How much of the seed for household use is damaged?  

**Description:** This variable indicates the extent of damage to the seed for household use kept in the storeroom. Only asked if 'Seed stock for household use' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `seed_sale_damage_store`  

**Question:** How much of the seed for sale is damaged?  

**Description:** This variable indicates the extent of damage to the seed for sale kept in the storeroom. Only asked if 'Seed stock for sale' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `other_items_damage_store`  

**Question:** How much of the other items is damaged?  

**Description:** This variable indicates the extent of damage to other items kept in the storeroom. Only asked if 'Other items' is selected in `rodent_damage_store_items`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

\centering
\normalsize 
\textcolor{blue!80!black}{\textbf{End of multiple room building repeat}}
\color{black}
\raggedright

\footnotesize  

\mydoublerule{}  

**Variable Name:** `building_name`  

**Question:** What buildings does this household have?  

**Description:** This variable captures the single room buildings present in the household.   

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Room or bedroom (Code: bedroom)  
- Option 2: Parlour (Code: parlour)  
- Option 3: Kitchen (Code: kitchen)  
- Option 4: Store (Code: store)  
- Option 5: Farm shed (Code: farm_shed)  
- Option 6: Hunting shed (Code: hunting_shed)  
- Option 7: Animal shed (Code: animal_shed)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `building_name_other`  

**Question:** Specify other building name  

**Description:** This variable allows specifying other building names if 'Other' is selected in `building_name`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `n_room`  

**Question:** How many buildings are used as rooms/bedrooms?  

**Description:** This variable indicates the number of buildings used as rooms or bedrooms. Only asked if 'Room or bedroom' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_room`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each building used as a room or bedroom. Only asked if there are multiple buildings used as rooms or bedrooms.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_parlour`  

**Question:** How many buildings are used as a parlour?  

**Description:** This variable indicates the number of buildings used as a parlour. Only asked if 'Parlour' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_parlour`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each building used as a parlour. Only asked if there are multiple buildings used as parlours.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_kitchen`  

**Question:** How many buildings are used as kitchens?  

**Description:** This variable indicates the number of buildings used as kitchens. Only asked if 'Kitchen' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_kitchen`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each building used as a kitchen. Only asked if there are multiple buildings used as kitchens.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_store`  

**Question:** How many buildings are used only as store rooms?  

**Description:** This variable indicates the number of buildings used only as store rooms. Only asked if 'Store' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_store`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each building used only as a store room. Only asked if there are multiple buildings used only as store rooms.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `building_ownership`  

**Question:** Ownership status of the building  

**Description:** This variable indicates the ownership status of the building.  

**Type of Data:** Single-select with four responses  

**Options for Responses:**  
- Option 1: Own themselves (Code: own_themselves)  
- Option 2: Another family member owns it (Code: own_family)  
- Option 3: Rented from a different household and different family (Code: rented)  
- Option 4: Other (Code: other)  

--- 

**Variable Name:** `n_farm_shed`  

**Question:** How many farm sheds are there?  

**Description:** This variable indicates the number of farm sheds. Only asked if 'Farm shed' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_farm`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each farm shed. Only asked if there are multiple farm sheds.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_hunting_shed`  

**Question:** How many hunting sheds are there?  

**Description:** This variable indicates the number of hunting sheds. Only asked if 'Hunting shed' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_hunting`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each hunting shed. Only asked if there are multiple hunting sheds.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_animal_shed`  

**Question:** How many animal sheds are there?  

**Description:** This variable indicates the number of animal sheds. Only asked if 'Animal shed' is selected in `building_name`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `same_construction_animal`  

**Question:** Is the construction the same for each of these?  

**Description:** This variable captures whether the construction is the same for each animal shed. Only asked if there are multiple animal sheds.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

\mydoublerule{}

\centering
\Large 
\textcolor{blue!80!black}{\textbf{Repeat Section: Single room buildings will be added, one per repeat}}
\color{black}
\raggedright
\footnotesize  

---

**Variable Name:** `building_purpose_single`  

**Question:** Building purpose  

**Description:** This variable captures the purpose of the single room building. Select all appropriate activities.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Sleeping (Code: sleeping)  
- Option 2: Food preparation (Code: food_preparation)  
- Option 3: Cooking (Code: cooking)  
- Option 4: Eating (Code: eating)  
- Option 5: Socialising/Parlour (Code: socialising_parlour)  
- Option 6: Cooked food storage (Code: cooked_food_storage)  
- Option 7: Packaged food storage (Noodle, Indomie etc.) (Code: packaged_food_storage)  
- Option 8: Crop storage (Garri, Rice, Yam etc.) (Code: crop_storage)  
- Option 9: Seed storage (Code: seed_storage)  
- Option 10: Animal storage (Chicken, Goat etc.) (Code: animal_storage)  
- Option 11: Other storage (Code: other_storage)  
- Option 12: Other (Code: other)  

--- 

**Variable Name:** `specify_building_purpose_single`  

**Question:** Specify other  

**Description:** This variable allows for specifying other purposes of the single room building. Only asked if Other is selected in `building_purpose_single`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `building_location_single`  

**Question:** Where is this building located?  

**Description:** This variable indicates the location of the single room building.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Within the compound (Code: compound)  
- Option 2: No compound, within the village (Code: no_compound)  
- Option 3: Elsewhere in the village, outside of the compound (Code: village)  
- Option 4: In the fields, outside of the compound (Code: fields)  
- Option 5: In a different village (Code: other_village)  
- Option 6: In a different town/city (Code: in_town)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `specify_building_location_single`  

**Question:** Specify other  

**Description:** This variable allows for specifying other locations of the single room building. Only asked if Other is selected in 	`building_location_single`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `building_type_single`  

**Question:** What type of building is this?  

**Description:** This variable indicates the type of the single room building.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Multi room building (Code: multi_room_building)  
- Option 2: Single room building (square) (Code: single_room_building_square)  
- Option 3: Single room building (circular) (Code: single_room_building_circular)  
- Option 4: Single room building (rounded corners) (Code: single_room_building_rounded)  
- Option 5: Other (Code: other)  

--- 

**Variable Name:** `specify_other_building`  

**Question:** Specify other type of building  

**Description:** This variable allows for specifying other types of the single room building. Only asked if Other is selected in `building_type_single`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `animal_structure`  

**Question:** Is there a structure to house animals attached to this building?  

**Description:** This variable indicates whether there is a structure to house animals attached to the single room building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `animals_in_structure`  

**Question:** What animals are kept in this structure?  

**Description:** This variable captures the animals kept in the structure attached to the single room building. Only asked if 'Yes' is selected in `animal_structure`.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Chicken (Code: chicken)  
- Option 2: Goat/Sheep (Code: goat)  
- Option 3: Cow (Code: cow)  
- Option 4: Pig (Code: pig)  
- Option 5: Duck/Fowl (Code: duck)  
- Option 6: Other (Code: other)  

--- 

**Variable Name:** `roof_material`  

**Question:** What is the roof made of?  

**Description:** This variable indicates the material used for the roof of the single room building.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Mat/thatch (Code: mat_thatch)  
- Option 2: Zinc/metal (Code: zinc_metal)  
- Option 3: Deck (Code: deck)  
- Option 4: None (Code: none)  
- Option 5: Other (Code: other)  

--- 

**Variable Name:** `roof_other_single`  

**Question:** Specify roof type  

**Description:** This variable allows for specifying other roof types if 'Other' is selected in `roof_material`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `wall_material`  

**Question:** What are the walls made of?  

**Description:** This variable captures the materials used for the walls of the single room building.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Mud block (Code: mud_block)  
- Option 2: Brick (Code: brick)  
- Option 3: Cement blocks (Code: cement_block)  
- Option 4: Plaster (Code: plaster)  
- Option 5: Wood (Slats, Lumber etc.) (Code: wood)  
- Option 6: Trees/Sticks (Code: wood_other)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `walls_other_single`  

**Question:** Specify walls type  

**Description:** This variable allows for specifying other wall types if 'Other' is selected in `wall_material`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `door_material`  

**Question:** What is the door of the main entrance made of?  

**Description:** This variable indicates the material used for the door of the main entrance of the single room building.   

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Wood (Code: wood)  
- Option 2: Metal (Code: metal)  
- Option 3: None (Code: none)  
- Option 4: Other (Code: other)  

--- 

**Variable Name:** `door_other_single`  

**Question:** Specify door material  

**Description:** This variable allows for specifying other door materials if 'Other' is selected in `door_material`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `window_material`  

**Question:** What are the windows made of?  

**Description:** This variable captures the materials used for the windows of the single room building.  

**Type of Data:** Multi-select  

**Options for Responses:**  
- Option 1: Permanently open (Code: permanently_open)  
- Option 2: Permanently closed (Code: permanently_closed)  
- Option 3: Wooden shutters (Code: wooden_shutters)  
- Option 4: Glass panes (Code: glass)  
- Option 5: Mosquito net (Code: screen)  
- Option 6: Metal grill/sheet (Code: metal)  
- Option 7: No windows (Code: none)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `specify_window_single`  

**Question:** Specify other  

**Description:** This variable allows for specifying other window materials if 'Other' is selected in `window_material`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `ceiling_material`  

**Question:** What material is used for the ceiling?  

**Description:** This variable indicates the material used for the ceiling of the single room building.  

**Type of Data:** Single-select  

**Options for Responses:**  
- Option 1: Mat/thatch (Code: mat_thatch)  
- Option 2: Wood (Code: wood)  
- Option 3: Cement (Code: cement)  
- Option 4: Synthetic (Code: synthetic)  
- Option 5: Sack bag/Carpet/Lino (Code: lining)  
- Option 6: No ceiling (Code: no_ceiling)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `specify_ceiling_single`  

**Question:** Specify other  

**Description:** This variable allows for specifying other ceiling materials if 'Other' is selected in `ceiling_material`.  

**Type of Data:** Free text  

--- 

**Variable Name:** `ceiling_storage_single`  

**Question:** Is there anything stored between the ceiling and the roof?  

**Description:** This variable indicates whether there is anything stored between the ceiling and the roof of the single room building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `storage_items_ceiling_single`  

**Question:** What is stored in this space?  

**Description:** This variable captures the items stored between the ceiling and the roof of the single room building. Multiple options can be selected, and it is only asked if 'Yes' is selected in `ceiling_storage_single`.  

**Type of Data:** Multi-select  

**Options for Responses:**    

- Option 1: Cooked food (Code: cooked_food)  
- Option 2: Uncooked food (Code: uncooked_food)  
- Option 3: Packaged food (Code: packaged_food)  
- Option 4: Crops for sale (Code: crops_for_sale)  
- Option 5: Crops for household use (Code: crops_for_household_use)  
- Option 6: Seeds for sale (Code: seeds_for_sale)  
- Option 7: Seeds for household use (Code: seeds_for_household_use)  
- Option 8: Clothing (Code: clothing)  
- Option 9: Other (Code: other)  

--- 

**Variable Name:** `ceiling_storage_other_single`  

**Question:** What other items are stored in the roof storage space?  

**Description:** Enter items, using a comma (,) to separate items. This question is asked only if 'Other' is selected in `ceiling_storage_single`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `floor_material`  

**Question:** What is the floor made of?  

**Description:** This variable captures the material of the floor. It is asked as a multiple-choice question.  

**Type of Data:** Multiple-select  

**Options for Responses:**  
- Option 1: Mud (Code: mud)  
- Option 2: Cement (Code: cement)  
- Option 3: Tile (Code: tile)  
- Option 4: Other (Code: other)  

--- 

**Variable Name:** `specify_floor_other_single`  

**Question:** Specify the floor material  

**Description:** This variable captures additional details about the floor material. It is asked only if 'Other' is selected in `floor_material`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `n_household_sleep_single`  

**Question:** How many people from this household sleep in this building?  

**Description:** This variable captures the number of people from this household who sleep in this building.  

**Type of Data:** Integer  

--- 

**Variable Name:** `other_household_sleep_single`  

**Question:** Do members of a different household sleep in this building?  

**Description:** This variable captures whether members of a different household sleep in this building. It is asked only if 'Sleeping' is selected in `building_purpose_single`.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `other_household_sleep_shared_single`  

**Question:** Do members of a different household sleep in the same space/place as members of this household?  

**Description:** This variable captures whether members of a different household sleep in the same space/place as members of this household. It is asked only if 'Yes' is selected in `other_household_sleep_single`.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `n_other_household_sleep_single`  

**Question:** How many members of a different household sleep in this building?  

**Description:** This variable captures the number of members of a different household who sleep in this building. It is asked only if 'Yes' is selected in `other_household_sleep_single`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `rodents_enter_building_single`  

**Question:** Do any rats enter this building?  

**Description:** This variable captures whether rats are known to enter the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Don't know (Code: unknown)  

--- 

**Variable Name:** `rodents_in_building_single`  

**Question:** Do any rats live in this building?  

**Description:** This variable captures whether rats are known to live in the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Don't know (Code: unknown)  

--- 

**Variable Name:** `rodents_in_building_evidence_single`  

**Question:** How do you know rats live here?  

**Description:** This variable captures the evidence of rats living in the building. It is asked only if 'Yes' is selected in `rodents_in_building_single`.  

**Type of Data:** Multiple-select  

**Options for Responses:**  
- Option 1: See live rats (Code: see_live_rats)  
- Option 2: See dead rats (Code: see_dead_rats)  
- Option 3: See rat urine (Code: see_rat_urine)  
- Option 4: See rat faeces (Code: see_rat_faeces)  
- Option 5: See rat burrows (Code: see_rat_burrows)  
- Option 6: Hear them (Code: hear_them)  
- Option 7: Smell them (Code: smell_them)  
- Option 8: Direct contact with rats (Code: direct_contact)  
- Option 9: Seen the damage they have done to items (Code: item_damage)  
- Option 10: Other (Code: other)  

--- 

**Variable Name:** `mastomys_single`  

**Question:** Do you notice a rat called Mastomys natalensis (the multimammate rat, or the rat with many offspring) in this building?  

**Description:** This variable captures whether you notice a specific type of rat in the building. It is asked if rats enter or live in the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Don't know (Code: unknown)  

--- 

**Variable Name:** `mastomys_timing_single`  

**Question:** What time of the day do you see this rat?  

**Description:** This variable captures the time of the day when you see the specific type of rat. It is asked only if 'Yes' is selected in `mastomys_single`.  

**Type of Data:** Single-select with three responses (Daytime, Nighttime, Anytime)  

**Options for Responses:**  
- Option 1: Daytime (Code: daytime)  
- Option 2: Nighttime (Code: nighttime)  
- Option 3: Anytime (Code: anytime)  

--- 

**Variable Name:** `mastomys_season_single`  

**Question:** Which season do you see them in?  

**Description:** This variable captures the season when you see the specific type of rat. It is asked only if 'Yes' is selected in `mastomys_single`.  

**Type of Data:** Single-select with three responses (Dry, Rainy, All seasons)  

**Options for Responses:**  
- Option 1: Dry (Code: dry)  
- Option 2: Rainy (Code: rainy)  
- Option 3: All seasons (Code: all_seasons)  

--- 

**Variable Name:** `sleep_in_kitchen_single`  

**Question:** How many members of this household sleep in the kitchen?  

**Description:** This variable captures the number of household members sleeping in the kitchen.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `food_inside_single`  

**Question:** Are ingredients or crops stored in this kitchen?  

**Description:** This variable indicates whether ingredients or crops are stored in the kitchen.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `cooked_inside_single`  

**Question:** Is cooked food stored in this building?  

**Description:** This variable indicates whether cooked food is stored in the building.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_damage_kitchen_single`  

**Question:** Do rats eat or destroy food or crops in the kitchen?  

**Description:** This variable indicates whether rats eat or destroy food or crops in the kitchen.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodent_damage_kitchen_items_single`  

**Question:** What do rats eat or destroy in the kitchen?  

**Description:** This variable captures what rats eat or destroy in the kitchen. It is asked only if 'Yes' is selected in `rodent_damage_kitchen_single`.  

**Type of Data:** Multiple-select  

**Options for Responses:**  
- Option 1: Prepared but uncooked food (Garri, Pounded Yam etc.) (Code: uncooked_food)  
- Option 2: Other ingredients for cooking (Spices, Dried Fish etc.) (Code: ingredients)  
- Option 3: Cooked food (Code: cooked_food)  
- Option 4: Rice for cooking (Code: rice)  
- Option 5: Yams for cooking (Code: yam)  
- Option 6: Groundnut for cooking (Code: groundnut)  
- Option 7: Other crops for cooking (Code: other_crops)  

--- 

**Variable Name:** `specify_other_kitchen_items_single`  

**Question:** Specify other  

**Description:** This variable allows specifying other items if selected in `rodent_damage_kitchen_items_single`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `ingredients_food_damage_single`  

**Question:** How much of the ingredients for food is damaged?  

**Description:** This variable captures the extent of damage to the ingredients for food, if any.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `cooked_food_damage_single`  

**Question:** How much of the cooked food is damaged?  

**Description:** This variable captures the extent of damage to the cooked food, if any.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `rice_damage_single`  

**Question:** How much of the rice is damaged?  

**Description:** This variable captures the extent of damage to the rice, if any.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `yam_damage_single`  

**Question:** How much of the yam is damaged?  

**Description:** This variable captures the extent of damage to the yam, if any.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**  
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `sleep_in_store_single`  

**Question:** Do any members of this household sleep in the storeroom?  

**Description:** This variable indicates whether any members of the household sleep in the storeroom.  

**Type of Data:** Single-select with three responses (Yes, No, Sometimes)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `n_sleep_in_store_single`  

**Question:** How many individuals from this household sleep in the storeroom(s)?  

**Description:** This variable captures the number of individuals from the household who sleep in the storeroom(s). It is asked only if 'Yes' is selected in `sleep_in_store_single`.  

**Type of Data:** Integer  

--- 

**Variable Name:** `cooked_food_in_store_single`  

**Question:** Do you ever store cooked food in this same store room?  

**Description:** This variable indicates whether cooked food is stored in the same storeroom.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**  
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `stored_inside_single`  

**Question:** Are any of the following stored in this building?  

**Description:** This variable captures items stored in the building.  

**Type of Data:** Multiple-select  

**Options for Responses:**  
- Option 1: Cooked food (Code: cooked_food)  
- Option 2: Ingredients for cooking (Code: ingredients)  
- Option 3: Packaged food (Code: packaged_food)  
- Option 4: Harvested crops for household use (Code: harvested_crops_use)  
- Option 5: Harvested crops for sale (Code: harvested_crops_sale)  
- Option 6: Seed stock for household use (Code: seed_use)  
- Option 7: Seed stock for sale (Code: seed_sale)  
- Option 8: Other items (Code: other)  

--- 

**Variable Name:** `other_stored_single`  

**Question:** Specify other items  

**Description:** This variable allows respondents to specify other items stored in the building. Only asked if Other items is selected in `stored_inside_single`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `crops_stored_single`  

**Question:** What types of crops?  

**Description:** This variable captures the types of crops stored in the building.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Rice (Code: rice)  
- Option 2: Maize/Corn (Code: maize_corn)  
- Option 3: Cassava (Code: cassava)  
- Option 4: Yams (Code: yam)  
- Option 5: Fruit (Code: fruit)  
- Option 6: Other (Code: other)  

--- 

**Variable Name:** `crops_stored_single_other`  

**Question:** Specify other crops  

**Description:** This variable allows respondents to specify other types of crops stored in the building. Only asked if Other is selected in `crops_stored_single`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `seed_stored_inside_single`  

**Question:** What types of seeds?  

**Description:** This variable captures the types of seeds stored in the building.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Rice (Code: rice)  
- Option 2: Maize/Corn (Code: maize_corn)  
- Option 3: Cassava (Code: cassava)  
- Option 4: Other (Code: other)  

--- 

**Variable Name:** `seed_stored_inside_other`  

**Question:** Specify other seeds  

**Description:** This variable allows respondents to specify other types of seeds stored in the building. Only asked if Other is selected in `seed_stored_inside_single`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_damage_store_single`  

**Question:** Do rats eat or destroy food or crops in the store?  

**Description:** This variable indicates whether rats cause damage to food or crops stored in the building.  

**Type of Data:** Single-select with three responses (Yes, No, Unknown)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Unknown (Code: unknown)  

--- 

**Variable Name:** `rodent_damage_store_items_single`  

**Question:** What do rats eat or destroy in this storeroom?  

**Description:** This variable captures the items that rats eat or destroy in the storeroom.  

**Options for Responses:**  
- Option 1: Cooked food (Code: cooked_food)  
- Option 2: Ingredients for cooking (Code: ingredients)  
- Option 3: Packaged food (Code: packaged_food)  
- Option 4: Harvested crops for household use (Code: harvested_crops_use)  
- Option 5: Harvested crops for sale (Code: harvested_crops_sale)  
- Option 6: Seed stock for household use (Code: seed_use)  
- Option 7: Seed stock for sale (Code: seed_sale)  
- Option 8: Other items (Code: other)  

--- 

**Variable Name:** `cooked_food_damage_store_single`  

**Question:** How much of the cooked food is damaged?  

**Description:** This variable captures the extent of damage to cooked food caused by rats in the storeroom. This question is only asked if 'Cooked food' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `ingredients_damage_store_single`  

**Question:** How much of the ingredients for cooking are damaged?  

**Description:** This variable captures the extent of damage to ingredients for cooking caused by rats in the storeroom. This question is only asked if 'Ingredients for cooking' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `packaged_food_damage_store_single`  

**Question:** How much of the packaged food is damaged?  

**Description:** This variable captures the extent of damage to packaged food caused by rats in the storeroom. This question is only asked if 'Packaged food' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `crops_use_damage_store_single`  

**Question:** How much of the crops for household use is damaged?  

**Description:** This variable captures the extent of damage to crops for household use caused by rats in the storeroom. This question is only asked if 'Harvested crops for household use' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `crops_sale_damage_store_single`  

**Question:** How much of the crops for sale is damaged?  

**Description:** This variable captures the extent of damage to crops for sale caused by rats in the storeroom. This question is only asked if 'Harvested crops for sale' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `seed_use_damage_store_single`  

**Question:** How much of the seed for household use is damaged?  

**Description:** This variable captures the extent of damage to seed for household use caused by rats in the storeroom. This question is only asked if 'Seed stock for household use' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `seed_sale_damage_store_single`  

**Question:** How much of the seed for sale is damaged?  

**Description:** This variable captures the extent of damage to seed for sale caused by rats in the storeroom. This question is only asked if 'Seed stock for sale' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  

--- 

**Variable Name:** `other_items_damage_store_single`  

**Question:** How much of the other items is damaged?  

**Description:** This variable captures the extent of damage to other items caused by rats in the storeroom. This question is only asked if 'Other items' is selected in the response to `rodent_damage_store_items_single`.  

**Type of Data:** Single-select with three responses (A bit (<25%), A lot (25-75%), Most (>75%))  

**Options for Responses:**    
- Option 1: A bit (<25%) (Code: a_bit_25)  
- Option 2: A lot (25-75%) (Code: a_lot_25_75)  
- Option 3: Most (>75%) (Code: most_75)  


\centering
\normalsize 
\textcolor{blue!80!black}{\textbf{End of single room building repeat}}
\color{black}
\raggedright

\footnotesize  

\mydoublerule{}  


**Variable Name:** `rodent_removal_questions`  

**Question:** Did the participant mention any awareness of rodents in their building in the above questions?  

**Description:** This variable captures whether the participant mentioned any awareness of rodents in their building in the preceding questions.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_removal_home`  

**Question:** Is there anything you do to remove rats that live in your home?  

**Description:** This variable captures whether the participant takes any action to remove rats that live in their home. This question is only asked if the participant mentioned awareness of rodents in their building in the preceding questions.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_removal_home_method`  

**Question:** How do you do this removal?  

**Description:** This variable captures the methods used by the participant to remove rats from their home. This question is only asked if the participant takes action to remove rats that live in their home.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Traps (Code: traps)  
- Option 2: Poison (Code: poison)  
- Option 3: Gumtrap (Rat bible) (Code: gumtrap)  
- Option 4: Sticks (Code: sticks)  
- Option 5: Cats (Code: cat)  
- Option 6: Dogs (Code: dog)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `rodent_removal_method_other`  

**Question:** Specify other  

**Description:** This variable captures other methods used by the participant to remove rats from their home. This question is only asked if 'Other' is selected in the response to `rodent_removal_home_method`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_remove_use`  

**Question:** What do you do with the rats you remove from your home?  

**Description:** This variable captures what the participant does with the rats they remove from their home. This question is only asked if the participant takes action to remove rats that live in their home.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Eat them (Code: eat_them)  
- Option 2: Sell them (Code: sell_them)  
- Option 3: Dispose of them (Code: dispose_them)  
- Option 4: Feed them to animals (Code: feed_them_to_animals)  
- Option 5: I do not contact the bodies of the rat (Code: no_contact)  

--- 

**Variable Name:** `rodent_remove_other`  

**Question:** Specify other  

**Description:** This variable captures other methods used by the participant to remove rats from their home. This question is only asked if 'Other' is selected in the response to `rodent_remove_use`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_mitigation`  

**Question:** Is there anything you do to stop rats damaging your items, food, crops, or seeds in this building? Is there anything you do to prevent rats accessing your home?  

**Description:** This variable captures whether the participant takes any action to prevent rats from damaging items, food, crops, or seeds in their building, or from accessing their home. This question is only asked if the participant mentioned any awareness of rodents in their building in the preceding questions.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_mitigation_method`  

**Question:** How do you do this?  

**Description:** This variable captures the methods used by the participant to mitigate the risk of rats damaging items, food, crops, or seeds in their building, or from accessing their home. This question is only asked if the participant takes action to prevent rats from damaging items, food, crops, or seeds in their building, or from accessing their home.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Store items that rats eat in containers (Code: containers)  
- Option 2: Seal holes/burrows (Code: seal_burrows)  
- Option 3: Replace wooden doors with metal doors (Code: convert_door)  
- Option 4: Make a concrete home (Code: upgrade_structure)  
- Option 5: Use cats (Code: cats)  
- Option 6: Use dogs (Code: dogs)  
- Option 7: None (Code: none)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `rodent_mitigation_other`  

**Question:** Specify other  

**Description:** This variable captures other methods used by the participant to mitigate the risk of rats damaging items, food, crops, or seeds in their building, or from accessing their home. This question is only asked if 'Other' is selected in the response to `rodent_mitigation_method`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_control_buildings`  

**Question:** Do you use these approaches in all of the buildings you access?  

**Description:** This variable captures whether the participant uses the approaches mentioned above in all of the buildings they access. This question is only asked if the participant takes action to remove rats that live in their home or takes measures to prevent rats from accessing their home.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_control_specific`  

**Question:** Which buildings do you use these approaches in?  

**Description:** This variable captures the specific buildings in which the participant uses the approaches mentioned above. This question is only asked if the participant does not use these approaches in all of the buildings they access.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Sleeping (Code: sleeping)  
- Option 2: Food preparation (Code: food_preparation)  
- Option 3: Cooking (Code: cooking)  
- Option 4: Eating (Code: eating)  
- Option 5: Socialising/Parlour (Code: socialising_parlour)  
- Option 6: Cooked food storage (Code: food_storage)  
- Option 7: Packaged food storage (Noodle, Indomie etc.) (Code: packaged_food_storage)  
- Option 8: Crop storage (Garri, Rice, Yam etc.) (Code: crop_storage)  
- Option 9: Seed storage (Code: seed_storage)  
- Option 10: Animal storage (Chicken, Goat etc.) (Code: animal_storage)  
- Option 11: Other storage (Code: other_storage)  
- Option 12: Other (Code: other)  

--- 

**Variable Name:** `cats`  

**Question:** Do you keep cats in this household?  

**Description:** This variable captures whether the participant keeps cats in their household.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `cats_inside`  

**Question:** Do cats ever go into your buildings?  

**Description:** This variable captures whether cats ever go into the participant's buildings.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `non_buildings`  

**Question:** Do you have any other spaces in your compound which you use to store food and/or crops which are not enclosed buildings? For example yam barns or any other buildings without roofs that have not been described above.  

**Description:** This variable captures whether the participant has any other spaces in their compound used for storing food and/or crops that are not enclosed buildings, such as yam barns or other structures without roofs that have not been described above.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `toilet`  

**Question:** What type of toilet do members of this household normally use?  

**Description:** This variable captures the type of toilet used by members of the household.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Go to the toilet in the bush/Open defecation (Code: field_defecation)  
- Option 2: In a trench or other open system (Code: open_system)  
- Option 3: In a pit latrine (Code: pit_latrine)  
- Option 4: In a toilet with plumbing (Code: toilet_plumbing)  
- Option 5: Other (Code: other)  

--- 

**Variable Name:** `specify_other_toilet`  

**Question:** Specify other  

**Description:** This variable captures other types of toilets used by members of the household. This question is only asked if 'Other' is selected in the response to `toilet`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `toilet_structure`  

**Question:** Is the toilet or bathroom a separate structure?  

**Description:** This variable captures whether the toilet or bathroom is a separate structure. This question is only asked if the toilet type includes an enclosed system, a pit latrine, or a toilet with plumbing.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `household_fields`  

**Question:** Does this household own or manage any fields? Include garden areas as a single field if they are near to each other.  

**Description:** This variable captures whether the household owns or manages any fields. This includes garden areas considered as a single field if they are near to each other.  

**Type of Data:** Single-select with three responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

\mydoublerule{}  

\centering
\Large 
\textcolor{blue!80!black}{\textbf{Repeat Section: Data on fields owned or managed by this household}}
\color{black}
\raggedright

\footnotesize  

--- 

**Variable Name:** `field_ownership`  

**Question:** Is this a rented field?  

**Description:** This variable captures whether the field is rented by the household.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `field_years`  

**Question:** How long, in years, have you rented this field for?  

**Description:** This variable captures the duration, in years, for which the field has been rented by the household. This question is only asked if the field is rented.  

**Type of Data:** Integer  

--- 

**Variable Name:** `field_shared`  

**Question:** At any point in the last 12 months did you hire other people from outside of the household to work in this field?  

**Description:** This variable captures whether the household hired people from outside of the household to work in the field during the last 12 months.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `field_type`  

**Question:** What type of field is this?  

**Description:** This variable captures the type of field.   

**Type of Data:** Single-select  

**Options for Responses:**    
- Option 1: Flat field (Code: flat)  
- Option 2: Mounded/Heaped/Ridges field (Code: mounded)  
- Option 3: Garden (Code: garden)  
- Option 4: Wet/Paddy field (swamp field) (Code: wet)  
- Option 5: Plantation (Code: plantation)  
- Option 6: Orchard (Code: orchard)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `field_type_specify`  

**Question:** Please specify.  

**Description:** This variable captures additional details about the type of field. This question is only asked if 'Other' is selected in the response to `field_type`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `field_crop`  

**Question:** What do you grow in this field? If multiple crops are grown in the same field select all of the appropriate options.  

**Description:** This variable captures the crops grown in the field.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Maize/Corn (Code: maize_corn)  
- Option 2: Rice (Code: rice)  
- Option 3: Cassava (Code: cassava)  
- Option 4: Yam (Code: yam)  
- Option 5: Fruit (Code: fruit)  
- Option 6: Vegetables (Code: vegetables)  
- Option 7: Cacao (Code: cacao)  
- Option 8: Peppers (Code: peppers)  
- Option 9: Groundnut (Code: groundnut)  
- Option 10: Okra (Code: okra)  
- Option 11: Bene seeds (Code: bene_seeds)  
- Option 12: Beans (Code: beans)  
- Option 13: Leafy greens (Code: leafy_greens)  
- Option 14: Sweet potato (Code: sweet_potato)  
- Option 15: Other (Code: other)  

--- 

**Variable Name:** `field_crop_other`  

**Question:** Specify other.  

**Description:** This variable captures other crops grown in the field. This question is only asked if 'Other' is selected in the response to `field_crop`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rat_field`  

**Question:** Do you notice rats in this field?  

**Description:** This variable captures whether the respondent notices rats in the field.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rat_field_evidence`  

**Question:** How do you know rats live here?  

**Description:** This variable captures the evidence of rats living in the field. Only asked if `rat_field` is answered Yes  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: See live rats (Code: see_live_rats)  
- Option 2: See dead rats (Code: see_dead_rats)  
- Option 3: See rat urine (Code: see_rat_urine)  
- Option 4: See rat faeces (Code: see_rat_faeces)  
- Option 5: See rat burrows (Code: see_rat_burrows)  
- Option 6: See the damage they do (Code: see_damage)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `rat_field_evidence_other`  

**Question:** Specify other.  

**Description:** This variable captures other evidence of rats living in the field. This question is only asked if 'Other' is selected in the response to `rat_field_evidence`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `mastomys_field`  

**Question:** Do you notice a rat called Mastomys natalensis (the multimammate rat, or the rat with many young) in this field?  

**Description:** This variable captures whether the respondent notices Mastomys natalensis in the field.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `mastomys_timing_field`  

**Question:** What time of the day do you see this rat?  

**Description:** This variable captures the time of day when the respondent sees Mastomys natalensis in the field. This question is only asked if 'Yes' is selected in the response to `mastomys_field`.  

**Type of Data:** Single-select  

**Options for Responses:**    
- Option 1: Daytime (Code: daytime)  
- Option 2: Nighttime (Code: nighttime)  
- Option 3: Anytime (Code: anytime)  

--- 

**Variable Name:** `mastomys_season_field`  

**Question:** Which season do you see them in?  

**Description:** This variable captures the season in which the respondent sees Mastomys natalensis in the field. This question is only asked if 'Yes' is selected in the response to `mastomys_field`.  

**Type of Data:** Single-select  

**Options for Responses:**    
- Option 1: Dry (Code: dry)  
- Option 2: Rainy (Code: rainy)  
- Option 3: All seasons (Code: all_seasons)  

--- 

**Variable Name:** `predators`  

**Question:** What predators do you notice in this field?  

**Description:** This variable captures the predators noticed in the field.  

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Bird of prey/Hawk/Raptor (Code: bop)  
- Option 2: Monkeys (Code: monkey)  
- Option 3: Feral dog/Wild dog (Code: feral_dog)  
- Option 4: Other (Code: other)  

--- 

**Variable Name:** `predation_other`  

**Question:** Specify other.  

**Description:** This variable captures other predators noticed in the field. This question is only asked if 'Other' is selected in the response to `predators`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `maize_field_damage`  

**Question:** How much of the Maize/Corn crop in the field is damaged by rats?  

**Description:** This variable captures the extent of damage to the Maize/Corn crop caused by rats. This question is asked if the respondent selects 'Maize/Corn' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `rice_field_damage`  

**Question:** How much of the rice harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the rice harvest caused by rats. This question is asked if the respondent selects 'Rice' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `cassava_field_damage`  

**Question:** How much of the cassava harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the cassava harvest caused by rats. This question is asked if the respondent selects 'Cassava' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `yam_field_damage`  

**Question:** How much of the yam harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the yam harvest caused by rats. This question is asked if the respondent selects 'Yam' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `fruit_field_damage`  

**Question:** How much of the fruit harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the fruit harvest caused by rats. This question is asked if the respondent selects 'Fruit' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `vegetable_field_damage`  

**Question:** How much of the vegetable harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the vegetable harvest caused by rats. This question is asked if the respondent selects 'Vegetables' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `cacao_field_damage`  

**Question:** How much of the cacao harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the cacao harvest caused by rats. This question is asked if the respondent selects 'Cacao' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `peppers_field_damage`  

**Question:** How much of the pepper harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the pepper harvest caused by rats. This question is asked if the respondent selects 'Peppers' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `groundnut_field_damage`  

**Question:** How much of the groundnut harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the groundnut harvest caused by rats. This question is asked if the respondent selects 'Groundnut' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `okra_field_damage`  

**Question:** How much of the okra harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the okra harvest caused by rats. This question is asked if the respondent selects 'Okra' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `bene_field_damage`  

**Question:** How much of the bene seed harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the bene seed harvest caused by rats. This question is asked if the respondent selects 'Bene Seeds' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `beans_field_damage`  

**Question:** How much of the bean harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the bean harvest caused by rats. This question is asked if the respondent selects 'Beans' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `greens_field_damage`  

**Question:** How much of the leafy greens harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the leafy greens harvest caused by rats. This question is asked if the respondent selects 'Leafy Greens' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `potato_field_damage`  

**Question:** How much of the sweet potato harvest is damaged by rats?  

**Description:** This variable captures the extent of damage to the sweet potato harvest caused by rats. This question is asked if the respondent selects 'Sweet Potato' in the `field_crop` variable.  

**Type of Data:** Range (Integer)  

**Options for Responses:**    
- Range: 1 to 5  
- 1: No damage by rodents  
- 5: There is nothing left after the rodents have damaged it  

--- 

**Variable Name:** `pesticide_use`  

**Question:** Do you use any of the following on this field?  

**Description:** This variable captures whether the respondent uses any pesticides on the field.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Rodenticide (Code: rodenticide)  
- Option 2: Pesticide (Code: pesticide)  
- Option 3: Herbicide (Code: herbicide)  
- Option 4: Insecticide (Code: insecticide)  
- Option 5: Other (Code: other)  

--- 

**Variable Name:** `pesticide_other`  

**Question:** Specify other.  

**Description:** This variable captures other pesticides used on the field. This question is only asked if 'Other' is selected in the response to `pesticide_use`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_removal_field`  

**Question:** Is there anything you do to remove rats that live in this field?  

**Description:** This variable captures whether the respondent takes any actions to remove rats from the field.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

**Condition:** This question is asked if the respondent notices rats in the field (`rat_field` equals 'yes').  

--- 

**Variable Name:** `rodent_removal_field_method`  

**Question:** How do you do this?  

**Description:** This variable captures the method used to remove rats from the field. This question is only asked if the respondent selects 'Yes' in the response to `rodent_removal_field`.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Traps (Code: traps)  
- Option 2: Poison (Code: poison)  
- Option 3: Gumtrap (Rat bible) (Code: gumtrap)  
- Option 4: Sticks (Code: sticks)  
- Option 5: Cats (Code: cat)  
- Option 6: Dogs (Code: dog)  
- Option 7: Other (Code: other)  

--- 

**Variable Name:** `rodent_removal_field_other`  

**Question:** Specify other.  

**Description:** This variable captures other methods used to remove rats from the field. This question is only asked if 'Other' is selected in the response to `rodent_removal_field_method`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_remove_use_field`  

**Question:** What do you do with the rats you remove from your field?  

**Description:** This variable captures what the respondent does with the rats removed from the field. This question is asked if the respondent selects 'Yes' in the response to `rodent_removal_field`.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Eat them (Code: eat_them)  
- Option 2: Sell them (Code: sell_them)  
- Option 3: Dispose of them (Code: dispose_them)  
- Option 4: Feed them to animals (Code: feed_them_to_animals)  
- Option 5: I do not contact the bodies of the rat (Code: no_contact)  
- Option 6: Other (Code: other)  

--- 

**Variable Name:** `rodent_mitigation_field`  

**Question:** Is there anything you do to stop rats damaging your crops in this field?  

**Description:** This variable captures whether the respondent takes any actions to prevent rats from damaging crops in the field.  

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

**Condition:** This question is asked if the respondent notices rats in the field (`rat_field` equals 'yes').  

--- 

**Variable Name:** `rodent_mitigation_method_field`  

**Question:** How do you do this?  

**Description:** This variable captures the method used to prevent rats from damaging crops in the field. This question is only asked if the respondent selects 'Yes' in the response to `rodent_mitigation_field`.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Store items that rats eat in containers (Code: containers)  
- Option 2: Seal holes/burrows (Code: seal_burrows)  
- Option 3: Replace wooden doors with metal doors (Code: convert_door)  
- Option 4: Make a concrete home (Code: upgrade_structure)  
- Option 5: Use cats (Code: cats)  
- Option 6: Use dogs (Code: dogs)  
- Option 7: None (Code: none)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `rodent_mitigation_field_other`  

**Question:** Specify other.  

**Description:** This variable captures other methods used to prevent rats from damaging crops in the field. This question is only asked if 'Other' is selected in the response to `rodent_mitigation_method_field`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `field_location`  

**Question:** How long does it take you to walk to the field?  

**Description:** This variable captures the time taken by the respondent to walk to the field, reported in minutes. Alternatively, it can be phrased as "If you were to leave for the field at 7 am, what time would you arrive there?" and the number of minutes then calculated.  

**Type of Data:** Integer  

--- 

**Variable Name:** `field_position`  

**Question:** Do you need to do any of the following to get to the field?  

**Description:** This variable captures the actions the respondent needs to take to reach the field.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Cross a river or stream (Code: river)  
- Option 2: Cross a tarred road (Code: road)  
- Option 3: Walk through a forest (Code: forest)  
- Option 4: Walk through other households' fields (Code: other_fields)  

**Condition:** This question is asked if the respondent's location to the field is not a compound (`field_location` is not 'compound').  

\centering
\normalsize
\textcolor{blue!80!black}{\textbf{End of field repeat}}
\color{black}
\raggedright

\footnotesize  

\mydoublerule{}  

**Variable Name:** `livestock`  

**Question:** Do you own any livestock animals?  

**Description:** This variable captures whether the respondent owns any livestock animals.  

**Type of Data:** Single-select with two responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `livestock_animals`  

**Question:** Which animals do you own?  

**Description:** This variable captures the types of animals owned by the respondent. This question is asked if the respondent answers 'Yes' to owning livestock (`livestock` equals 'yes').  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Chicken (Code: chicken)  
- Option 2: Goat/Sheep (Code: goat)  
- Option 3: Cow (Code: cow)  
- Option 4: Pig (Code: pig)  
- Option 5: Duck/Fowl (Code: duck)  
- Option 6: Other (Code: other)  

--- 

**Variable Name:** `livestock_other`  

**Question:** Specify other.  

**Description:** This variable captures other types of livestock owned by the respondent. This question is only asked if 'Other' is selected in the response to `livestock_animals`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `livestock_sleep`  

**Question:** Where do your livestock normally sleep at night?  

**Description:** This variable captures the sleeping locations of the respondent's livestock. This question is asked if the respondent answers 'Yes' to owning livestock (`livestock` equals 'yes').  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: In a room where people sleep (Code: house)  
- Option 2: In a shed for chickens (Code: chicken_shed)  
- Option 3: In a shed for goats/sheep (Code: goat_shed)  
- Option 4: In a structure for pigs (Code: pig_sty)  
- Option 5: Outside (Code: outside)  
- Option 6: Other (Code: other)  

--- 

**Variable Name:** `livestock_sleep_other`  

**Question:** Specify other.  

**Description:** This variable captures other sleeping locations of the respondent's livestock. This question is only asked if 'Other' is selected in the response to `livestock_sleep`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `livestock_sleep_species`  

**Question:** Do animals of different species ever sleep in the same building/structure?  

**Description:** This variable captures whether animals of different species ever sleep in the same building/structure. This question is asked if the respondent answers 'Yes' to owning livestock (`livestock` equals 'yes') and the livestock do not sleep outside (`livestock_sleep` does not equal 'outside').  

**Type of Data:** Single-select with three responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  
- Option 3: Sometimes (Code: sometimes)  

--- 

**Variable Name:** `meal_location`  

**Question:** Does this household eat their meals inside or outside?  

**Description:** This variable captures whether the household eats their meals inside, outside, or both.  

**Type of Data:** Single-select  

**Options for Responses:**    
- Option 1: Inside (Code: inside)  
- Option 2: Outside (Code: outside)  
- Option 3: Both inside and outside (Code: inside_outside)  

--- 

**Variable Name:** `storage_cooked_containers`  

**Question:** What containers is cooked food stored in?  

**Description:** This variable captures the containers used to store cooked food.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Pot (Code: pot)  
- Option 2: Pot with lid (Code: pot_lid)  
- Option 3: Jerry can (Code: fuel_can)  
- Option 4: Jerry can with lid (Code: fuel_can_lid)  
- Option 5: Flask (Code: flask)  
- Option 6: Flask with lid (Code: flask_lid)  
- Option 7: Cooler (Code: cooler)  
- Option 8: None (Code: none)  
- Option 9: Not applicable (Code: not_applicable)  
- Option 10: Other (Code: other)  

--- 

**Variable Name:** `storage_cooked_other`  

**Question:** Specify other.  

**Description:** This variable captures other types of containers used to store cooked food. This question is only asked if 'Other' is selected in the response to `storage_cooked_containers`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `storage_packaged_containers`  

**Question:** What containers are packaged food stored in?  

**Description:** This variable captures the containers used to store packaged food.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Packaging or wrapper it came in (Code: wrapper)  
- Option 2: Nylon/Plastic bag (Code: nylon)  
- Option 3: Container (Code: container)  
- Option 4: Container with lid (Code: container_lid)  
- Option 5: Plastic container without lid (Code: plastic_container)  
- Option 6: Plastic container with lid (Code: plastic_container_lid)  
- Option 7: Cupboard (Code: cupboard)  
- Option 8: None (Code: none)  
- Option 9: Not applicable (Code: not_applicable)  
- Option 10: Other (Code: other)  

--- 

**Variable Name:** `storage_packaged_other`  

**Question:** Specify other.  

**Description:** This variable captures other types of containers used to store packaged food. This question is only asked if 'Other' is selected in the response to `storage_packaged_containers`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `storage_seed_crop_containers_c`  

**Question:** What containers are crops or seeds that are used for cooking stored in?  

**Description:** This variable captures the containers used to store crops or seeds that are used for cooking.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Sack bag (Code: sack)  
- Option 2: Bucket (Code: bucket)  
- Option 3: Bucket with a lid (Code: bucket_lid)  
- Option 4: Clay pot (Code: clay_pot)  
- Option 5: Clay pot with a lid (Code: clay_pot_lid)  
- Option 6: None (Code: none)  
- Option 7: Not applicable (Code: not_applicable)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `storage_c_other`  

**Question:** Specify other.  

**Description:** This variable captures other types of containers used to store crops or seeds that are used for cooking. This question is only asked if 'Other' is selected in the response to `storage_seed_crop_containers_c`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `storage_seed_crop_containers_g`  

**Question:** What containers are crops or seeds that are used for growing stored in?  

**Description:** This variable captures the containers used to store crops or seeds that are used for growing.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Sack bag (Code: sack)  
- Option 2: Bucket (Code: bucket)  
- Option 3: Bucket with a lid (Code: bucket_lid)  
- Option 4: Clay pot (Code: clay_pot)  
- Option 5: Clay pot with a lid (Code: clay_pot_lid)  
- Option 6: None (Code: none)  
- Option 7: Not applicable (Code: not_applicable)  
- Option 8: Other (Code: other)  

--- 

**Variable Name:** `storage_g_other`  

**Question:** Specify other.  

**Description:** This variable captures other types of containers used to store crops or seeds that are used for growing. This question is only asked if 'Other' is selected in the response to `storage_seed_crop_containers_g`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `food_resources`  

**Question:** In the past 30 days, was there ever no food to eat of any kind in your house because of lack of resources to get food?  

**Description:** This variable captures whether there was ever a situation in the past 30 days where there was no food to eat in the household due to lack of resources.  

**Type of Data:** Single-select with two responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `food_resources_frequency`  

**Question:** How often did this happen in the past 30 days?  

**Description:** This variable captures the frequency of situations where there was no food to eat in the household due to lack of resources. This question is asked if the respondent answers 'Yes' to `food_resources`.  

**Type of Data:** Single-select with three responses  

**Options for Responses:**    
- Option 1: Rarely (1-2 times) (Code: rarely)  
- Option 2: Sometimes (3-10 times) (Code: sometimes)  
- Option 3: Often (more than 10 times) (Code: often)  

--- 

**Variable Name:** `food_sleep`  

**Question:** In the past 30 days, did you or any household member go to sleep at night hungry because there was not enough food?  

**Description:** This variable captures whether any household member went to sleep at night hungry due to insufficient food in the past 30 days.  

**Type of Data:** Single-select with two responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `food_sleep_frequency`  

**Question:** How often did this happen in the past 30 days?  

**Description:** This variable captures the frequency of situations where any household member went to sleep at night hungry due to insufficient food in the past 30 days. This question is asked if the respondent answers 'Yes' to `food_sleep`.  

**Type of Data:** Single-select with three responses  

**Options for Responses:**    
- Option 1: Rarely (1-2 times) (Code: rarely)  
- Option 2: Sometimes (3-10 times) (Code: sometimes)  
- Option 3: Often (more than 10 times) (Code: often)  

--- 

**Variable Name:** `food_day`  

**Question:** In the past 30 days, did you or any household member go a whole day and night without eating anything at all because there was not enough food?  

**Description:** This variable captures whether any household member went a whole day and night without eating anything at all due to insufficient food in the past 30 days.  

**Type of Data:** Single-select with two responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `food_day_frequency`  

**Question:** How often did this happen in the past 30 days?  

**Description:** This variable captures the frequency of situations where any household member went a whole day and night without eating anything at all due to insufficient food in the past 30 days. This question is asked if the respondent answers 'Yes' to `food_day`.  

**Type of Data:** Single-select with three responses  

**Options for Responses:**    
- Option 1: Rarely (1-2 times) (Code: rarely)  
- Option 2: Sometimes (3-10 times) (Code: sometimes)  
- Option 3: Often (more than 10 times) (Code: often)  

--- 

**Variable Name:** `household_items`  

**Question:** Select each of the following items that your household owns.  

**Description:** This variable captures the household items owned by the respondent's household.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Radio (Code: radio)  
- Option 2: Casette player/recorder (Code: casette_player)  
- Option 3: TV (Code: tv)  
- Option 4: Wooden chairs (Code: wooden_chairs)  
- Option 5: Upholstered chairs (Code: upholstered_chairs)  
- Option 6: Cane chairs (Code: cane_chairs)  
- Option 7: Wooden cupboard (Code: wooden_cupboard)  
- Option 8: Cane cupboard (Code: cane_cupboard)  
- Option 9: Wooden bed (Code: wooden_bed)  
- Option 10: Metal bed (Code: metal_bed)  

\mydoublerule{}  

\centering
\Large
\textcolor{blue!80!black}{\textbf{Repeat Section: Cultural and Health practices involving rodents}}
\color{black}
\raggedright
\Large  
\footnotesize  

--- 

**Variable Name:** `rodent_culture_health`  

**Question:** Do you people have any cultural practices (festivals, charms, sacrifices) or health practices that use rats or animals that resemble rats?  

**Description:** This variable captures whether there are cultural or health practices in the community that involve the use of rats or animals resembling rats.  

**Type of Data:** Single-select with two responses  

**Options for Responses:**    
- Option 1: Yes (Code: yes)  
- Option 2: No (Code: no)  

--- 

**Variable Name:** `rodent_culture_health_name`  

**Question:** What is the name of this practice?  

**Description:** This variable captures the name of the cultural or health practice involving rats or animals resembling rats. This question is asked if the respondent answers 'Yes' to `rodent_culture_health`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `rodent_name_detail`  

**Question:** What rat species is this information about?  

**Description:** This variable captures the rat species relevant to the cultural or health practice. This question is asked if the respondent answers 'Yes' to `rodent_culture_health`.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Ntaali (Code: ntaali)  
- Option 2: Ektupo (Code: ektupo)  
- Option 3: Nkapfu (Code: nkapfu)  
- Option 4: Oginyi (Code: oginyi)  
- Option 5: Ikpo (Code: ikpo)  
- Option 6: Okoror (Code: okoror)  
- Option 7: Oriku (Code: oriku)  
- Option 8: Odupfu (Code: odupfu)  
- Option 9: Ekwata (Code: ekwata)  
- Option 10: Kpev (Code: kpev)  
- Option 11: Agundu (Code: agundu)  
- Option 12: Julie (Code: julie)  
- Option 13: Akpezinga/Abrazinga (Code: akpezinga)  
- Option 14: Mbam/Ngbam (Code: mbam)  
- Option 15: Nyongu (Code: nyongu)  
- Option 16: Sam (Code: sam)  
- Option 17: Agbacha (Code: agbacha)  
- Option 18: Torhe (Code: torhe)  
- Option 19: Fashon (Code: fashion)  
- Option 20: Ubina (Code: ubina)  
- Option 21: Irom (Code: irom)  
- Option 22: Imanava (Code: imanava)  

--- 

**Variable Name:** `part_of_rodent`  

**Question:** What parts of the rat are used for this practice?  

**Description:** This variable captures the parts of the rat used in the cultural or health practice. This question is asked if the respondent answers 'Yes' to `rodent_culture_health`.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Meat of rat (Code: meat)  
- Option 2: Skin of rat (Code: skin)  
- Option 3: Bones/teeth/claws of rat (Code: hard_part)  
- Option 4: Whole rat (Code: whole_animal)  
- Option 5: Organs of the rat (Code: internal_organs)  
- Option 6: Faeces of the rat (Code: faeces)  
- Option 7: Fat of the rat (Code: fat)  
- Option 8: Fur of the rat (Code: fur)  
- Option 9: Don't know (Code: unknown)  
- Option 10: Rat blood (Code: blood)  
- Option 11: Other (Code: other)  

--- 

**Variable Name:** `part_of_rodent_other`  

**Question:** Specify other.  

**Description:** This variable captures other parts of the rat used in the cultural or health practice. This question is asked if 'Other' is selected in the response to `part_of_rodent`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `purpose_of_rodent`  

**Question:** What is the purpose of using this part?  

**Description:** This variable captures the purpose of using the specified part of the rat in the cultural or health practice.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `prepare_rodent`  

**Question:** How is the rat prepared?  

**Description:** This variable captures the method of preparation for the rat used in the cultural or health practice.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Live (Code: live)  
- Option 2: Raw (Code: raw)  
- Option 3: Passive heat (under sun) (Code: passive_heat)  
- Option 4: Direct heat (above fire) (Code: direct_heat)  
- Option 5: Liquor (Code: liquor)  
- Option 6: Other (Code: other)  
- Option 7: Don't know (Code: unknown)  

--- 

**Variable Name:** `prepare_rodent_other`  

**Question:** Specify other.  

**Description:** This variable captures other methods of preparing the rat used in the cultural or health practice. This question is asked if 'Other' is selected in the response to `prepare_rodent`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `administering_rodent`  

**Question:** How is the rat prescribed/administered?  

**Description:** This variable captures the method of administration for the rat used in the cultural or health practice.  

**Type of Data:** Multiple-select  

**Options for Responses:**    
- Option 1: Oral (Code: oral)  
- Option 2: Topical (skin) (Code: topical_skin)  
- Option 3: Topical (eye) (Code: topical_eye)  
- Option 4: Topical (inhaled) (Code: topical_inhaled)  
- Option 5: Enema (Code: enema)  
- Option 6: Subcutaneous (Code: subcutaneous)  
- Option 7: Intravenous (Code: intravenous)  
- Option 8: Other (Code: other)  
- Option 9: Don't know (Code: unknown)  

--- 

**Variable Name:** `administering_rodent_other`  

**Question:** Specify other.  

**Description:** This variable captures other methods of administering the rat used in the cultural or health practice. This question is asked if 'Other' is selected in the response to `administering_rodent`.  

**Type of Data:** Free-text  

\centering
\normalsize 
\textcolor{blue!80!black}{\textbf{End of Health and Cultural practices repeat}}
\color{black}
\raggedright
\footnotesize  

\mydoublerule{}  

--- 

**Variable Name:** `latitude`  

**Question:** Latitude (first row on the GPS next to N)  

**Description:** This variable captures the latitude coordinate of the household, taken while standing in front of the main doorway into the household. The latitude value typically begins with '06'.  

**Type of Data:** Decimal  

--- 

**Variable Name:** `longitude`  

**Question:** Longitude (second row on the GPS next to E)  

**Description:** This variable captures the longitude coordinate of the household, taken while standing in front of the main doorway into the household. The longitude value typically begins with '08'.  

**Type of Data:** Decimal  

\mydoublerule{}  

\Large  
\centering
\textcolor{blue!80!black}{\textbf{Repeat Section: Household photographs}}
\color{black}
\footnotesize  
\raggedright

--- 

**Variable Name:** `photos_acceptable`  

**Question:** Are you able to take photos of the area surrounding the household and inside the house?  

**Description:** This variable captures whether the respondent is able to take photos of the area surrounding the household and inside the house. If 'Yes' is selected, the respondent is prompted to take photos. If 'No' is selected, no further action is required.   

**Type of Data:** Single-select with two responses (Yes, No)  

**Options for Responses:**    
- Option 1: Yes  
- Option 2: No  

**Notes:** Make sure that when taking photos, faces of any individuals are not included. For inside photos, particularly focus on the kitchen, sleeping area, and area where food, crops, or seeds are stored. Also, take photos of any known rat burrows.  

--- 

**Variable Name:** `photo_inside`  

**Question:** Photo (inside)  

**Description:** This variable captures a photo taken inside the household. (Associated Logic: This variable is associated with the group `inside_photos`, initiated when the respondent indicates they are able to take photos (`photos_acceptable` = 'yes').)  

**Type of Data:** Image  

--- 

**Variable Name:** `photo_inside_name`  

**Question:** What is this a photo of?  

**Description:** This variable captures the description of the photo taken inside the household. (Associated Logic: This variable is associated with the group `inside_photos`, initiated when the respondent indicates they are able to take photos (`photos_acceptable` = 'yes').)  

**Type of Data:** Text  

--- 

**Variable Name:** `photo_outside`  

**Question:** Photo (outside)  

**Description:** This variable captures a photo taken outside the household. (Associated Logic: This variable is associated with the group `outside_photos`, initiated when the respondent indicates they are able to take photos (`photos_acceptable` = 'yes').)  

**Type of Data:** Image  

--- 

**Variable Name:** `photo_outside_name`  

**Question:** What is this a photo of?  

**Description:** This variable captures the description of the photo taken outside the household. (Associated Logic: This variable is associated with the group `outside_photos`, initiated when the respondent indicates they are able to take photos (`photos_acceptable` = 'yes').)  

**Type of Data:** Text  

**Notes:** For outside photos, pictures of the different buildings that are part of the household, nearby gardens, farmland, or bush are desired.  

\centering
\normalsize
\textcolor{blue!80!black}{\textbf{End of Household photographs}}
\color{black}
\raggedright

\footnotesize  

\mydoublerule{}  

--- 

**Variable Name:** `surroundings_household`  

**Question:** What is in the nearby surrounding of this household?  

**Description:** This variable captures the elements present in the nearby surroundings of the household. Respondents can select multiple options.   

**Type of Data:** Multi-select  

**Options for Responses:**    
- Option 1: Another compound (Code: another_compound)
- Option 2: Other buildings not part of this household (Code: other_buildings)
- Option 3: Gardens (Code: gardens)
- Option 4: Farms (Code: farms)
- Option 5: Bush (Code: bush)
- Option 6: Forest (Code: forest)
- Option 7: Yam barn (Code: yam_barn)
- Option 8: Other (Code: other)

**Notes:** This completes the survey for this household. Offer to answer any questions they may have. Thank the participants and move on to the next household.  

--- 

**Variable Name:** `surroundings_outside_other`  

**Question:** Specify other  

**Description:** This variable captures other elements present in the nearby surroundings of the household, if 'Other' is selected in the response to `surroundings_household`.  

**Type of Data:** Free-text  

--- 

**Variable Name:** `notes`  

**Question:** Feel free to add any notes you want the team to know about this household.  

**Description:** This variable allows the respondent to add any additional notes about the household.  

**Type of Data:** Free-text  

:::  

Variable names and response codes are available from the XLSForm of the questionnaire. The variable name is stored in the `name` column of the `survey` sheet. For the responses (`choices` sheet), the `list_name` is associated with the `type` column in the `survey` sheet. The response values and labels are in the `choices` sheet columns named `name` and `label` respectively.

### Individual questionnaire:  

Linking IDs to samples?  

### Human serology  

### Rodent trapping  

### Rodent serology/PCR  

### Other  
